### ISSUE TITLE
iOS 7 Support

### ISSUE THREAD

**Issue by akramhussein** [giacgbj/UIImage-Swift-Extensions#2]
Hey - Thanks for this port. Quick question, any specific technical reasons the port is targetted only at iOS 8?

**Comment by giacgbj** [comment]
Hi, as far as I know, Cocoapods >=0.36 requires iOS >= 8.0.

**Comment by akramhussein** [comment]
Fair enough!

**Comment by giacgbj** [comment]
You can include the sources manually, as many other developer suggest. 
I know it's not extremely elegant, but it seems the only "clean" way.
