### ISSUE TITLE
Would it be possible to share the scheme?

### ISSUE THREAD

**Issue by flockoffiles** [giacgbj/UIImage-Swift-Extensions#5]
Would it be possible to share the scheme, so that the project could be built with Carthage?
Thanks!

**Comment by giacgbj** [comment]
@flockoffiles, I've never used Carthage and I simply don't know how it works :). According to https://github.com/Carthage/Carthage#share-your-xcode-schemes I should share the scheme, which is what I think I did. Can you confirm it, so I can close this ticket and release a new version?
